# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92a6924fa66be9f60d844783a2d982bb8dae8b368af6b051ad906bf9662f29f72f274e7f8fac40da7b3b0aa129f534e1ad52b8e4798085bb77def9c03f682115

test:
  secret_key_base: fc8fabbb6ff02c9aaf7b0e51121c23edb6d5078c892ade01a7c8dc8e4b275e72b87d960a0b4e3700ccc550df0dcc2b177ac84210194c7c84da123d026c24278c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
